'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider as NextThemesProvider } from 'next-themes';
import { type ThemeProviderProps } from 'next-themes/dist/types';
import JotaiProvider from './components/JotaiProvider';
import ConvexClientProvider from '@/app/components/ConvexClientProvider';
import { Toaster } from '@/components/ui/toaster';

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('h-screen font-sans antialiased', inter.variable)}>
        <Toaster />
        <JotaiProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </ThemeProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
