'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider as NextThemesProvider } from 'next-themes';
import { type ThemeProviderProps } from 'next-themes/dist/types';

import NextAuthProvider from './components/NextAuthProvider';
import JotaiProvider from './components/JotaiProvider';

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('h-screen font-sans antialiased', inter.variable)}>
        <NextAuthProvider>
          <JotaiProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='light'
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </JotaiProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
